#!/bin/sh
# This script sets appropriate permissions for files on webservers (i.e. none for anyone outside of me, except for a list of exceptions)

# Check to make sure has all its arguments
if [ "$#" -ne 3 ]; then
	echo "Illegal number of arguments"
	exit 1
fi
	
# Sets all files to be invisible to the outside
find . -mindepth 1 -type d -exec chmod 750 {} \;
find . -type f -exec chmod 640 {} \;

# Sets exceptional files to be visible to the outside in a read-only capacity
if [ -f "$1" ]; then
	cat "$1" | xargs chmod 644
else
	echo "Not an acceptable input file for files"
fi

# Sets exceptional folders to be visible to the outside in a read/execute-only capacity
if [ -f "$2" ]; then
	cat "$2" | xargs chmod 755
else
	echo "Not an acceptable input file for folders"
fi

# Sets this script to be executable
if [ -f "$3" ]; then
	cat "$3" | xargs chmod 750
else
	echo "Not an acceptable input file for folders"
fi
	
